name: test

on: [ push ]

jobs:
  test:
    strategy:
      matrix:
        python-version: [3.7, 3.8]
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install modules
        run: make install
      - name: Run CI test
        run: make ci
